### ISSUE TITLE
epic: items for production-ready claim process 

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#59]
This issue is meant to track the required work items that need to be addressed in order for contract's behavior wrt the claiming process can be considered to be in a completed state.

- [ ] update contract start arguments to contain a merkle hash of all eligible recipients.
- [ ] check users validity proof against the merkle hash passed into the contract
- [ ] book keeping for claimed addresses
- [ ] update offer logic so that tokens are distributed to valid claimants using postal service mechanism
