### ISSUE TITLE
mainnet 2 task tracker table 

### ISSUE THREAD

**Issue by tgrecojs** [lari-labs/dapp-ertp-airdrop#93]
## Task list

- [x] [linting rules](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/commit/c043a83b805240867c70ef4b25b87cafd6c65fc1)
- [x] #102
- [ ] [contract pause functionality](#100)
- [ ] [deployment test](#99) 
- [ ] RPC rate limiting 
- [ ] Deployment to public testnet
- [ ] E2E Demo

cc @otoole-brendan

**Comment by dckc** [comment]
I suggest using a [github task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists)

In particular, 

 - [ ] #31

**Comment by dckc** [comment]
re linting... #44 is a withdrawn PR. citing that as support that it's complete is odd.

**Comment by dckc** [comment]
> I suggest using a [github task list](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists)

I suppose that doesn't provide status.

Github project boards support status nicely.

And an MN2 checklist review milestone would make sense.

**Comment by dckc** [comment]
[The milestone](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/milestone/1) looks good. I suggest closing this.

If you'd like to track in-progress vs. backlog, I suggest using a Github project board.

**Comment by tgrecojs** [comment]
sounds good 👍. closing @dckc 

[this milestone](https://github.com/hindley-milner-systems/dapp-ertp-airdrop/milestone/1) will take this issues place.
